include "root" {
  path = find_in_parent_folders("root.hcl")
}

# This unit talks to Cloudflare, not AWS — override the inherited aws provider
# (generated by root.hcl) with the Cloudflare provider so no AWS creds are needed
# here. Auth is the CLOUDFLARE_API_TOKEN env var (loaded from infra/.env by mise);
# the token must have Access → Apps and Policies → Edit, on top of the Pages
# scope used by the deploy. (OTP login needs no Identity Providers scope.)
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    provider "cloudflare" {}
  EOF
}

inputs = {
  cloudflare_account_id = get_env("CLOUDFLARE_ACCOUNT_ID")
  access_domain         = "ai.element-22.com"
  email_domain          = "element-22.com"
  session_duration      = "24h"
}
